image: python:3

before_script:
  - pip install -r requirements.txt

stages:
  - test
  - deploy
  
test:
  stage: test
  script:
  - pip install pylint
  - pylint -d C,R NHSABot/*.py

deploy:
  stage: deploy
  before_script:
    - 'apt-get update -y && apt-get install openssh-client rsync'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
  script:
  - echo "Initiating deployment..."
  - ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "[ -d ~/NHSABot ] && rm -r ~/NHSABot" 
  - rsync -p --chmod=0700 -e "ssh -p $SSH_PORT" -rz ../NHSABot $SSH_USER@$SSH_HOST:~/
  environment:
    name: production
  only:
  - master